# Generated by Django 5.2.1 on 2025-10-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_news_remove_blogvideo_section_alter_blogpost_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=255)),
                ("host", models.CharField(max_length=150)),
                ("event_type", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("reward", models.BooleanField(default=False)),
                ("location", models.CharField(max_length=255)),
                ("campfire_link", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
